import { createElement } from 'lwc';
import QR_Code_Generator_LWC from 'c/qR_Code_Generator_LWC';

describe('c-q-r-code-generator-lwc', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-q-r-code-generator-lwc', {
            is: QR_Code_Generator_LWC
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});